# Generated by Django 5.0.2 on 2024-02-25 00:19

import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("delivery", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="delivery",
            managers=[
                ("active", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterField(
            model_name="delivery",
            name="status",
            field=models.CharField(
                choices=[
                    ("Active", "Active"),
                    ("Assigned", "Assigned to Carrier"),
                    ("Accepted", "Accepted by Carrier"),
                    ("Gained", "Gained from an offer"),
                    ("In transit", "In transit"),
                    ("Complete", "Complete"),
                    ("Dropped", "Dropped"),
                    ("Cancelled", "Cancelled"),
                ],
                default="Active",
                max_length=100,
                verbose_name="Status",
            ),
        ),
    ]
