# Generated by Django 4.2.10 on 2024-03-20 13:10

import django.contrib.auth.models
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("Individual", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="individual",
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name="individual",
            name="date_joined",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="date joined"
            ),
        ),
        migrations.AddField(
            model_name="individual",
            name="groups",
            field=models.ManyToManyField(
                blank=True,
                related_name="individual_groups",
                related_query_name="individual",
                to="auth.group",
                verbose_name="groups",
            ),
        ),
        migrations.AddField(
            model_name="individual",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="individual",
            name="is_admin",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="individual",
            name="is_staff",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="individual",
            name="is_superuser",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="individual",
            name="last_login",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="last login"
            ),
        ),
        migrations.AddField(
            model_name="individual",
            name="last_name",
            field=models.CharField(
                blank=True, max_length=150, verbose_name="last name"
            ),
        ),
        migrations.AddField(
            model_name="individual",
            name="password",
            field=models.CharField(
                blank=True,
                default="",
                max_length=128,
                null=True,
                verbose_name="Password",
            ),
        ),
        migrations.AddField(
            model_name="individual",
            name="password_reset_token",
            field=models.CharField(blank=True, default="", max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="individual",
            name="user_permissions",
            field=models.ManyToManyField(
                blank=True,
                related_name="individual_user_permissions",
                related_query_name="individual",
                to="auth.permission",
                verbose_name="user permissions",
            ),
        ),
    ]
