# Generated by Django 4.2.10 on 2024-03-20 12:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Business",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "business_name",
                    models.CharField(
                        db_index=True, max_length=255, verbose_name="Business Name"
                    ),
                ),
                (
                    "contact_person",
                    models.CharField(
                        db_index=True, max_length=255, verbose_name="Contact Person"
                    ),
                ),
                (
                    "business_email",
                    models.EmailField(
                        db_index=True, max_length=255, verbose_name="Business Email"
                    ),
                ),
                (
                    "business_phone",
                    models.CharField(
                        blank=True,
                        max_length=30,
                        null=True,
                        verbose_name="Business Phone",
                    ),
                ),
                (
                    "website",
                    models.URLField(blank=True, null=True, verbose_name="Website"),
                ),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="images/"),
                ),
                (
                    "sequence",
                    models.PositiveSmallIntegerField(
                        db_index=True, editable=False, unique=True
                    ),
                ),
                (
                    "has_loading_dock",
                    models.BooleanField(
                        choices=[(False, "No"), (True, "Yes")],
                        default=False,
                        verbose_name="Loading Dock",
                    ),
                ),
                (
                    "has_forklift",
                    models.BooleanField(
                        choices=[(False, "No"), (True, "Yes")],
                        default=False,
                        verbose_name="Forklift",
                    ),
                ),
                (
                    "has_ramp",
                    models.BooleanField(
                        choices=[(False, "No"), (True, "Yes")],
                        default=False,
                        verbose_name="Ramp",
                    ),
                ),
            ],
            options={
                "verbose_name": "Business (Shipper)",
                "verbose_name_plural": "Businesses (Shippers)",
            },
        ),
        migrations.CreateModel(
            name="TypeOfIndustry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=200, unique=True, verbose_name="Name"),
                ),
            ],
            options={
                "verbose_name": "Type of industry",
            },
        ),
        migrations.CreateModel(
            name="ShipperEquipment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("type", models.CharField(max_length=100)),
                ("number", models.IntegerField()),
                (
                    "business",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="equipments",
                        to="Business.business",
                    ),
                ),
            ],
            options={
                "verbose_name": "Shipper Equipment",
                "verbose_name_plural": "Shipper Equipments",
            },
        ),
        migrations.CreateModel(
            name="BusinessAddress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "line1",
                    models.CharField(
                        max_length=255, verbose_name="First line of address"
                    ),
                ),
                (
                    "line2",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Second line of address",
                    ),
                ),
                (
                    "city",
                    models.CharField(blank=True, max_length=255, verbose_name="City"),
                ),
                (
                    "state",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="State"
                    ),
                ),
                (
                    "postcode",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=64,
                        null=True,
                        verbose_name="Zip Code",
                    ),
                ),
                (
                    "search_text",
                    models.TextField(
                        editable=False,
                        verbose_name="Search text - used only for searching addresses",
                    ),
                ),
                (
                    "business",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="address",
                        to="Business.business",
                        verbose_name="Business",
                    ),
                ),
            ],
            options={
                "verbose_name": "Business's address",
                "default_permissions": ["view", "change", "delete"],
            },
        ),
        migrations.CreateModel(
            name="BusinessTypeOfIndustry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "TypeOfIndustry",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Business.typeofindustry",
                        verbose_name="Type of industry",
                    ),
                ),
                (
                    "business",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="Type_of_industries",
                        to="Business.business",
                        verbose_name="Business",
                    ),
                ),
            ],
            options={
                "verbose_name": "Business type of industry",
                "unique_together": {("business", "TypeOfIndustry")},
            },
        ),
    ]
