# Generated by Django 4.2.10 on 2024-05-03 15:20

import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_person', models.CharField(db_index=True, max_length=255, verbose_name='Contact Person')),
                ('website', models.URLField(blank=True, null=True, verbose_name='Website')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('has_loading_dock', models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], verbose_name='Loading Dock')),
                ('has_forklift', models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], verbose_name='Forklift')),
                ('has_ramp', models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], verbose_name='Ramp')),
                ('sequence', models.PositiveSmallIntegerField(db_index=True, editable=False, unique=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Date created')),
            ],
            options={
                'verbose_name': 'Business',
                'verbose_name_plural': 'Businesses',
            },
        ),
        migrations.CreateModel(
            name='Individual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parking_available', models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], verbose_name='Parking available')),
                ('easy_access_to_loading', models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], verbose_name='Easy access to loading')),
            ],
            options={
                'verbose_name': 'Individual',
                'verbose_name_plural': 'Individuals',
            },
        ),
        migrations.CreateModel(
            name='TypeOfIndustry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'Type of industry',
                'verbose_name_plural': 'types of industries',
            },
        ),
        migrations.CreateModel(
            name='ShipperUser',
            fields=[
            ],
            options={
                'verbose_name': 'Shipper',
                'verbose_name_plural': 'Shippers',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Shipper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('B', 'Business'), ('V', 'Individual')], max_length=20, verbose_name='Type')),
                ('name', models.CharField(db_index=True, max_length=255, verbose_name='Name')),
                ('email_address', models.EmailField(db_index=True, max_length=255, verbose_name='Business Email')),
                ('phone_number', models.CharField(max_length=30, verbose_name='Business Phone')),
                ('sequence', models.PositiveSmallIntegerField(db_index=True, editable=False, unique=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Date created')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='shipper_profile', to='shipper.shipperuser')),
            ],
            options={
                'verbose_name': 'Shipper',
                'verbose_name_plural': 'Shippers',
            },
        ),
        migrations.CreateModel(
            name='IndividualAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line1', models.CharField(max_length=255, verbose_name='First line of address')),
                ('line2', models.CharField(blank=True, max_length=255, null=True, verbose_name='Second line of address')),
                ('city', models.CharField(blank=True, max_length=255, verbose_name='City')),
                ('state', models.CharField(blank=True, max_length=255, null=True, verbose_name='State')),
                ('postcode', models.CharField(blank=True, db_index=True, max_length=64, null=True, verbose_name='Zip Code')),
                ('search_text', models.TextField(editable=False, verbose_name='Search text - used only for searching addresses')),
                ('individual', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='address', to='shipper.individual', verbose_name='Individual')),
            ],
            options={
                'verbose_name': 'Individual Zip Code',
                'verbose_name_plural': 'Individual Zip Codes',
            },
        ),
        migrations.AddField(
            model_name='individual',
            name='shipper',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='shipper.shipper', verbose_name='Shipper'),
        ),
        migrations.CreateModel(
            name='BusinessAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line1', models.CharField(max_length=255, verbose_name='First line of address')),
                ('line2', models.CharField(blank=True, max_length=255, null=True, verbose_name='Second line of address')),
                ('city', models.CharField(blank=True, max_length=255, verbose_name='City')),
                ('state', models.CharField(blank=True, max_length=255, null=True, verbose_name='State')),
                ('postcode', models.CharField(blank=True, db_index=True, max_length=64, null=True, verbose_name='Zip Code')),
                ('search_text', models.TextField(editable=False, verbose_name='Search text - used only for searching addresses')),
                ('business', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='address', to='shipper.business', verbose_name='Business')),
            ],
            options={
                'verbose_name': 'Business addresses',
            },
        ),
        migrations.AddField(
            model_name='business',
            name='shipper',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='shipper.shipper'),
        ),
        migrations.AddField(
            model_name='business',
            name='type_of_industry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shipper.typeofindustry', verbose_name='Type of industry'),
        ),
    ]
