# Generated by Django 4.2.10 on 2024-03-06 16:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shipper', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Individual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255)),
                ('phone', models.CharField(max_length=30)),
                ('parking_available', models.BooleanField(default=False)),
                ('easy_access_to_loading', models.BooleanField(default=False)),
                ('sequence', models.PositiveSmallIntegerField(db_index=True, editable=False, unique=True)),
                ('shipper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shipper.shipper')),
            ],
        ),
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(max_length=255)),
                ('contact_person', models.CharField(max_length=255)),
                ('business_email', models.EmailField(max_length=255)),
                ('business_phone', models.CharField(blank=True, max_length=30, null=True)),
                ('website', models.URLField(blank=True, null=True)),
                ('sequence', models.PositiveSmallIntegerField(db_index=True, editable=False, unique=True)),
                ('shipper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shipper.shipper')),
            ],
        ),
    ]
