# Generated by Django 4.2.10 on 2024-03-11 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipper', '0003_remove_individual_shipper_delete_business_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shipper',
            name='name',
        ),
        migrations.AddField(
            model_name='shipper',
            name='business_name',
            field=models.CharField(db_index=True, default=1, max_length=255, verbose_name='Business Name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shipper',
            name='contact_person',
            field=models.CharField(db_index=True, default=1, max_length=255, verbose_name='Contact Person'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shipper',
            name='type_of_industry',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Type of Industry'),
        ),
    ]
