# Generated by Django 4.2.10 on 2024-03-11 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipper', '0004_remove_shipper_name_shipper_business_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipper',
            name='business_email',
            field=models.EmailField(db_index=True, default=1, max_length=255, verbose_name='Business Email'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shipper',
            name='business_phone',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Business Phone'),
        ),
        migrations.AddField(
            model_name='shipper',
            name='sequence',
            field=models.PositiveSmallIntegerField(db_index=True, default=1, editable=False, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shipper',
            name='website',
            field=models.URLField(blank=True, null=True, verbose_name='Website'),
        ),
    ]
