# Generated by Django 4.2.10 on 2024-03-08 00:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("carrier", "0001_initial"),
        ("shipper", "0004_business_businessaddress_businesstypeofindustry_and_more"),
        ("delivery", "0008_alter_deliveryaddress_shipper"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Shipper",
        ),
        migrations.AddField(
            model_name="shipperequipment",
            name="business",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="equipments",
                to="shipper.business",
            ),
        ),
        migrations.AddField(
            model_name="individualpreferredcarrier",
            name="carrier",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="carrier.carrier",
                verbose_name="Preferred Carrier",
            ),
        ),
        migrations.AddField(
            model_name="individualpreferredcarrier",
            name="individual",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="preferred_carriers",
                to="shipper.individual",
                verbose_name="Individual",
            ),
        ),
        migrations.AddField(
            model_name="individualdelivery",
            name="assigned_carrier",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="carrier.carrier",
                verbose_name="Assigned Carrier",
            ),
        ),
        migrations.AddField(
            model_name="individualdelivery",
            name="individual",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="deliveries",
                to="shipper.individual",
                verbose_name="Individual",
            ),
        ),
        migrations.AddField(
            model_name="individualaddress",
            name="individual",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="address",
                to="shipper.individual",
                verbose_name="Individual",
            ),
        ),
        migrations.AddField(
            model_name="businesstypeofindustry",
            name="TypeOfIndustry",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="shipper.typeofindustry",
                verbose_name="Type of industry",
            ),
        ),
        migrations.AddField(
            model_name="businesstypeofindustry",
            name="business",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="Type_of_industries",
                to="shipper.business",
                verbose_name="Business",
            ),
        ),
        migrations.AddField(
            model_name="businessaddress",
            name="business",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="address",
                to="shipper.business",
                verbose_name="Business",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="businesstypeofindustry",
            unique_together={("business", "TypeOfIndustry")},
        ),
    ]
