# Generated by Django 4.2.10 on 2024-03-13 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipper', '0005_shipper_business_email_shipper_business_phone_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shipper',
            name='business_email',
        ),
        migrations.RemoveField(
            model_name='shipper',
            name='business_name',
        ),
        migrations.RemoveField(
            model_name='shipper',
            name='business_phone',
        ),
        migrations.RemoveField(
            model_name='shipper',
            name='contact_person',
        ),
        migrations.RemoveField(
            model_name='shipper',
            name='sequence',
        ),
        migrations.RemoveField(
            model_name='shipper',
            name='type_of_industry',
        ),
        migrations.RemoveField(
            model_name='shipper',
            name='website',
        ),
        migrations.AddField(
            model_name='shipper',
            name='name',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
