# Generated by Django 4.2.10 on 2024-03-08 00:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shipper", "0005_delete_shipper_shipperequipment_business_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Shipper",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name="businessaddress",
            name="business",
        ),
        migrations.AlterUniqueTogether(
            name="businesstypeofindustry",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="businesstypeofindustry",
            name="TypeOfIndustry",
        ),
        migrations.RemoveField(
            model_name="businesstypeofindustry",
            name="business",
        ),
        migrations.RemoveField(
            model_name="individualaddress",
            name="individual",
        ),
        migrations.RemoveField(
            model_name="individualdelivery",
            name="assigned_carrier",
        ),
        migrations.RemoveField(
            model_name="individualdelivery",
            name="individual",
        ),
        migrations.RemoveField(
            model_name="individualpreferredcarrier",
            name="carrier",
        ),
        migrations.RemoveField(
            model_name="individualpreferredcarrier",
            name="individual",
        ),
        migrations.RemoveField(
            model_name="shipperequipment",
            name="business",
        ),
    ]
