# Generated by Django 4.2.10 on 2024-03-08 00:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("delivery", "0012_alter_deliveryaddress_shipper"),
        ("shipper", "0006_shipper_remove_businessaddress_business_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Business",
        ),
        migrations.DeleteModel(
            name="BusinessAddress",
        ),
        migrations.DeleteModel(
            name="BusinessTypeOfIndustry",
        ),
        migrations.DeleteModel(
            name="Individual",
        ),
        migrations.DeleteModel(
            name="IndividualAddress",
        ),
        migrations.DeleteModel(
            name="IndividualDelivery",
        ),
        migrations.DeleteModel(
            name="IndividualPreferredCarrier",
        ),
        migrations.DeleteModel(
            name="ShipperEquipment",
        ),
        migrations.DeleteModel(
            name="TypeOfIndustry",
        ),
    ]
