# Generated by Django 4.2.10 on 2024-03-20 10:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("delivery", "0013_shipper_alter_deliveryaddress_shipper"),
        ("carrier", "0009_merge_20240313_0916"),
        ("shipper", "0007_delete_business_delete_businessaddress_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Business",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "business_name",
                    models.CharField(
                        db_index=True, max_length=255, verbose_name="Business Name"
                    ),
                ),
                (
                    "contact_person",
                    models.CharField(
                        db_index=True, max_length=255, verbose_name="Contact Person"
                    ),
                ),
                (
                    "business_email",
                    models.EmailField(
                        db_index=True, max_length=255, verbose_name="Business Email"
                    ),
                ),
                (
                    "business_phone",
                    models.CharField(
                        blank=True,
                        max_length=30,
                        null=True,
                        verbose_name="Business Phone",
                    ),
                ),
                (
                    "website",
                    models.URLField(blank=True, null=True, verbose_name="Website"),
                ),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="images/"),
                ),
                (
                    "sequence",
                    models.PositiveSmallIntegerField(
                        db_index=True, editable=False, unique=True
                    ),
                ),
                (
                    "has_loading_dock",
                    models.BooleanField(
                        choices=[(False, "No"), (True, "Yes")],
                        default=False,
                        verbose_name="Loading Dock",
                    ),
                ),
                (
                    "has_forklift",
                    models.BooleanField(
                        choices=[(False, "No"), (True, "Yes")],
                        default=False,
                        verbose_name="Forklift",
                    ),
                ),
                (
                    "has_ramp",
                    models.BooleanField(
                        choices=[(False, "No"), (True, "Yes")],
                        default=False,
                        verbose_name="Ramp",
                    ),
                ),
            ],
            options={
                "verbose_name": "Business (Shipper)",
                "verbose_name_plural": "Businesses (Shippers)",
            },
        ),
        migrations.CreateModel(
            name="BusinessAddress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "line1",
                    models.CharField(
                        max_length=255, verbose_name="First line of address"
                    ),
                ),
                (
                    "line2",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Second line of address",
                    ),
                ),
                (
                    "city",
                    models.CharField(blank=True, max_length=255, verbose_name="City"),
                ),
                (
                    "state",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="State"
                    ),
                ),
                (
                    "postcode",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=64,
                        null=True,
                        verbose_name="Zip Code",
                    ),
                ),
                (
                    "search_text",
                    models.TextField(
                        editable=False,
                        verbose_name="Search text - used only for searching addresses",
                    ),
                ),
                (
                    "business",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="address",
                        to="shipper.business",
                        verbose_name="Business",
                    ),
                ),
            ],
            options={
                "verbose_name": "Business's address",
                "default_permissions": ["view", "change", "delete"],
            },
        ),
        migrations.CreateModel(
            name="BusinessTypeOfIndustry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
            options={
                "verbose_name": "Business type of industry",
            },
        ),
        migrations.CreateModel(
            name="Individual",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(max_length=255, verbose_name="First Name"),
                ),
                ("email", models.EmailField(max_length=254, verbose_name="Email")),
                ("phone", models.CharField(max_length=30, verbose_name="Phone")),
                (
                    "parking_available",
                    models.BooleanField(
                        choices=[("no", "No"), ("yes", "Yes")],
                        default="no",
                        max_length=5,
                        verbose_name="Parking available",
                    ),
                ),
                (
                    "easy_access_to_loading",
                    models.BooleanField(
                        choices=[("no", "No"), ("yes", "Yes")],
                        default="no",
                        max_length=5,
                        verbose_name="Easy access to loading",
                    ),
                ),
                (
                    "sequence",
                    models.PositiveSmallIntegerField(
                        db_index=True, editable=False, unique=True
                    ),
                ),
            ],
            options={
                "verbose_name": "Individual Profile",
                "verbose_name_plural": "Individual Profiles",
            },
        ),
        migrations.CreateModel(
            name="IndividualAddress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "line1",
                    models.CharField(
                        max_length=255, verbose_name="First line of address"
                    ),
                ),
                (
                    "line2",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Second line of address",
                    ),
                ),
                (
                    "city",
                    models.CharField(blank=True, max_length=255, verbose_name="City"),
                ),
                (
                    "state",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="State"
                    ),
                ),
                (
                    "postcode",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=64,
                        null=True,
                        verbose_name="Zip Code",
                    ),
                ),
                (
                    "search_text",
                    models.TextField(
                        editable=False,
                        verbose_name="Search text - used only for searching addresses",
                    ),
                ),
                (
                    "individual",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="address",
                        to="shipper.individual",
                        verbose_name="Individual",
                    ),
                ),
            ],
            options={
                "verbose_name": "Individual's address",
                "default_permissions": ["view", "change", "delete"],
            },
        ),
        migrations.CreateModel(
            name="IndividualDelivery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("origin", models.CharField(max_length=255, verbose_name="Origin")),
                (
                    "destination",
                    models.CharField(max_length=255, verbose_name="Destination"),
                ),
                ("status", models.CharField(max_length=100, verbose_name="Status")),
                ("pickup_date", models.DateTimeField(verbose_name="Pick Up Date")),
                ("delivery_date", models.DateTimeField(verbose_name="Delivery Date")),
                ("offers", models.IntegerField(default=0, verbose_name="Offers")),
                (
                    "assigned_carrier",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="carrier.carrier",
                        verbose_name="Assigned Carrier",
                    ),
                ),
                (
                    "individual",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="deliveries",
                        to="shipper.individual",
                        verbose_name="Individual",
                    ),
                ),
            ],
            options={
                "verbose_name": "Individual Delivery",
                "verbose_name_plural": "Individual Deliveries",
            },
        ),
        migrations.CreateModel(
            name="IndividualPreferredCarrier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "carrier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="carrier.carrier",
                        verbose_name="Preferred Carrier",
                    ),
                ),
                (
                    "individual",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="preferred_carriers",
                        to="shipper.individual",
                        verbose_name="Individual",
                    ),
                ),
            ],
            options={
                "verbose_name": "Preferred Carrier",
                "verbose_name_plural": "Preferred Carriers",
            },
        ),
        migrations.CreateModel(
            name="ShipperEquipment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("type", models.CharField(max_length=100)),
                ("number", models.IntegerField()),
                (
                    "business",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="equipments",
                        to="shipper.business",
                    ),
                ),
            ],
            options={
                "verbose_name": "Shipper Equipment",
                "verbose_name_plural": "Shipper Equipments",
            },
        ),
        migrations.CreateModel(
            name="TypeOfIndustry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=200, unique=True, verbose_name="Name"),
                ),
            ],
            options={
                "verbose_name": "Type of industry",
            },
        ),
        migrations.DeleteModel(
            name="Shipper",
        ),
        migrations.AddField(
            model_name="businesstypeofindustry",
            name="TypeOfIndustry",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="shipper.typeofindustry",
                verbose_name="Type of industry",
            ),
        ),
        migrations.AddField(
            model_name="businesstypeofindustry",
            name="business",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="Type_of_industries",
                to="shipper.business",
                verbose_name="Business",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="businesstypeofindustry",
            unique_together={("business", "TypeOfIndustry")},
        ),
    ]
