# Generated by Django 4.2.10 on 2024-05-03 15:20

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.DecimalField(decimal_places=2, max_digits=11, verbose_name='Rate')),
                ('weight', models.DecimalField(decimal_places=2, max_digits=11, verbose_name='Weight (lbs)')),
                ('width', models.DecimalField(decimal_places=2, max_digits=11, verbose_name='Width')),
                ('height', models.DecimalField(decimal_places=2, max_digits=11, verbose_name='Height')),
                ('depth', models.DecimalField(decimal_places=2, max_digits=11, verbose_name='Depth')),
                ('description', models.TextField(verbose_name='Description of Delivery')),
                ('hazmat', models.BooleanField(choices=[(False, 'No'), (True, 'Yes')], verbose_name='Hazmat')),
                ('pick_up_date', models.DateTimeField(verbose_name='Pick up date')),
                ('pick_up_instructions', models.TextField(blank=True, null=True, verbose_name='Pick up instructions')),
                ('drop_off_date', models.DateTimeField(verbose_name='Drop off Date')),
                ('drop_off_instructions', models.TextField(blank=True, null=True, verbose_name='Drop off instructions')),
                ('number', models.CharField(db_index=True, max_length=100, unique=True, verbose_name='Delivery ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Assigned', 'Assigned to Carrier'), ('Accepted', 'Accepted by Carrier'), ('Gained', 'Gained from an offer'), ('In transit', 'In transit'), ('Complete', 'Complete'), ('Dropped', 'Dropped'), ('Cancelled', 'Cancelled')], default='Active', max_length=100, verbose_name='Status')),
            ],
            options={
                'verbose_name': 'Delivery',
                'verbose_name_plural': 'Deliveries',
                'ordering': ['-date_created'],
                'default_permissions': ['view', 'change', 'delete'],
            },
            managers=[
                ('active', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='DeliveryAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line1', models.CharField(max_length=255, verbose_name='First line of address')),
                ('line2', models.CharField(blank=True, max_length=255, null=True, verbose_name='Second line of address')),
                ('city', models.CharField(blank=True, max_length=255, verbose_name='City')),
                ('state', models.CharField(blank=True, max_length=255, null=True, verbose_name='State')),
                ('postcode', models.CharField(blank=True, db_index=True, max_length=64, null=True, verbose_name='Zip Code')),
                ('search_text', models.TextField(editable=False, verbose_name='Search text - used only for searching addresses')),
                ('name', models.CharField(db_index=True, max_length=100, verbose_name='Name/Business')),
                ('type', models.CharField(choices=[('Pick up', 'Pick up'), ('Drop off', 'Drop off')], max_length=100, verbose_name='Type')),
                ('contact_person', models.CharField(db_index=True, max_length=100, verbose_name='Contact person')),
                ('phone_number', models.CharField(blank=True, max_length=30, null=True, verbose_name='Phone number')),
            ],
            options={
                'verbose_name': 'Delivery address',
                'verbose_name_plural': 'Delivery addresses',
                'default_permissions': ['view'],
            },
        ),
        migrations.CreateModel(
            name='DeliveryStatusChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_status', models.CharField(blank=True, max_length=100, null=True, verbose_name='Old Status')),
                ('new_status', models.CharField(blank=True, max_length=100, null=True, verbose_name='New Status')),
                ('date_created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Date Created')),
                ('delivery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_changes', to='delivery.delivery', verbose_name='Delivery')),
            ],
            options={
                'verbose_name': 'Delivery Status Change',
                'verbose_name_plural': 'Delivery Status Changes',
                'ordering': ['-date_created'],
                'default_permissions': ['view'],
            },
        ),
        migrations.CreateModel(
            name='DeliveryPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='')),
                ('delivery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='delivery.delivery')),
            ],
        ),
    ]
