# Generated by Django 4.2.10 on 2024-05-03 15:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('delivery', '0001_initial'),
        ('shipper', '0001_initial'),
        ('equipment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryaddress',
            name='shipper',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='shipper.shipper', verbose_name='Shipper'),
        ),
        migrations.AddField(
            model_name='delivery',
            name='drop_off_address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='drop_off_deliveries', to='delivery.deliveryaddress', verbose_name='Drop off Address'),
        ),
        migrations.AddField(
            model_name='delivery',
            name='pick_up_address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pick_up_deliveries', to='delivery.deliveryaddress', verbose_name='Pick Up Address'),
        ),
        migrations.AddField(
            model_name='delivery',
            name='recommended_vehicles',
            field=models.ManyToManyField(to='equipment.vehicletype', verbose_name='Recommended Vehicles'),
        ),
        migrations.AddField(
            model_name='delivery',
            name='shipper_business',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='business_deliveries', to='shipper.business', verbose_name='Business Shipper'),
        ),
        migrations.AddField(
            model_name='delivery',
            name='shipper_individual',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='individual_deliveries', to='shipper.individual', verbose_name='Individual Shipper'),
        ),
    ]
