# Generated by Django 4.2.10 on 2024-03-03 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0004_alter_delivery_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='delivery',
            options={'default_permissions': ['view', 'change', 'delete'], 'ordering': ['-date_created'], 'verbose_name': 'Delivery', 'verbose_name_plural': 'Deliveries'},
        ),
    ]
