# Generated by Django 4.2.10 on 2024-03-08 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carrier', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrier',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='carrier',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='carrier',
            name='email',
            field=models.EmailField(blank=True, max_length=255, null=True, unique=True, verbose_name='Business email'),
        ),
        migrations.AlterField(
            model_name='carrier',
            name='website',
            field=models.URLField(blank=True, max_length=255, null=True, unique=True, verbose_name='Website'),
        ),
    ]
