# Generated by Django 4.2.10 on 2024-03-11 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carrier', '0002_carrier_is_active_carrier_is_admin_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carrier',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='carrier',
            name='is_admin',
        ),
        migrations.AlterField(
            model_name='carrier',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Business email'),
        ),
        migrations.AlterField(
            model_name='carrier',
            name='website',
            field=models.URLField(blank=True, null=True, verbose_name='Website'),
        ),
    ]
