# Generated by Django 4.2.10 on 2024-03-11 14:26

import django.contrib.auth.models
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("carrier", "0002_carrier_groups_carrier_is_active_carrier_is_admin_and_more"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="carrier",
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
