# Generated by Django 4.2.10 on 2024-03-11 14:28

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("carrier", "0003_alter_carrier_managers"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="carrier",
            managers=[],
        ),
    ]
