# Generated by Django 4.2.10 on 2024-03-13 09:11

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("carrier", "0006_alter_carrier_managers_carrier_date_joined_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="carrier",
            name="username",
        ),
    ]
