# Generated by Django 4.2.10 on 2024-03-13 09:12

from django.db import migrations
from django.contrib.auth.models import User

def set_default_username(apps, schema_editor):
    Carrier = apps.get_model('carrier', 'Carrier')
    for carrier in Carrier.objects.all():
        if not carrier.username:
            carrier.username = carrier.email
            carrier.save()

class Migration(migrations.Migration):

    dependencies = [
        ('carrier', '0006_alter_carrier_managers_carrier_date_joined_and_more'),
    ]

    operations = [
        migrations.RunPython(set_default_username),
    ]
