# Generated by Django 4.2.10 on 2024-03-13 09:16

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("carrier", "0007_remove_carrier_username"),
        ("carrier", "0008_auto_20240313_0912"),
    ]

    operations = []
